"""Generate synthetic background demand for the pittsburgh_oakland scenario (no measured counts).

Every road that enters the network at its edge is an origin and every road that leaves it is a
destination. An origin's volume is a per-lane rate for its OSM road class times its lane count;
it is spread over the destinations in proportion to their own capacity weight, skipping U-turns
back out the way it came, trips shorter than MIN_ROUTE_M and destinations under MIN_SHARE.
Flows use per-second insertion probabilities (Poisson-like arrivals), like downtown_grid.

The signal timing in the network is sized to this demand, so build_network.py regenerates it;
run this directly only to try another scale without retiming.

Usage:
    python simulation/scenarios/pittsburgh_oakland/build_demand.py [--scale 0.55]
"""

from __future__ import annotations

import argparse
import collections
from pathlib import Path

import sumolib  # bundled with eclipse-sumo

HERE = Path(__file__).resolve().parent
NET = HERE.parents[1] / "networks" / "pittsburgh_oakland" / "oakland.net.xml"

# 0.55 gives ~2,500 veh/h: busy but stable (no gridlock or teleports over two simulated hours)
DEFAULT_SCALE = 0.55
# Flows stop at this time and the network then empties for good. It was 24 h, which an always-on service reaches after
# 90 minutes at 16x; 7 days is 10 h at 16x. The service also resets an idle twin long before either (twin_refresh_s).
HORIZON_S = 7 * 24 * 3600
# veh/h entering per lane, by OSM road class (a rough capacity ladder, not counts)
CLASS_VPH_PER_LANE = {
    "trunk": 380,
    "primary": 300,
    "secondary": 220,
    "tertiary": 120,
    "unclassified": 40,
    "residential": 25,
    "living_street": 10,
}
OTHER_VPH_PER_LANE = 20
MIN_SHARE = 0.02  # drop destinations that would get under 2% of an origin's volume
MIN_ROUTE_M = 250  # shorter trips barely touch the network


def road_class(edge) -> str:
    return edge.getType().split("|")[-1].replace("highway.", "").replace("_link", "")


def weight(edge) -> float:
    return CLASS_VPH_PER_LANE.get(road_class(edge), OTHER_VPH_PER_LANE) * edge.getLaneNumber()


def boundary_edges(net) -> tuple[list, list]:
    """Entries have no inflow other than their own reverse direction; exits no outflow other than theirs."""

    def others(edges, edge) -> list:
        return [e for e in edges if e.getFromNode() != edge.getToNode() or e.getToNode() != edge.getFromNode()]

    edges = [e for e in net.getEdges(withInternal=False) if e.allows("passenger")]
    entries = [e for e in edges if not others(e.getFromNode().getIncoming(), e)]
    exits = [e for e in edges if not others(e.getToNode().getOutgoing(), e)]
    return entries, exits


def flows(net, scale: float) -> list[tuple[str, str, str, float]]:
    entries, exits = boundary_edges(net)
    out = []
    for origin in entries:
        candidates = []
        for dest in exits:
            if dest.getFromNode() == origin.getToNode() or dest.getToNode() == origin.getFromNode():
                continue  # a U-turn back out where it came in
            path, _cost = net.getFastestPath(origin, dest, vClass="passenger")
            if not path or sum(e.getLength() for e in path) < MIN_ROUTE_M:
                continue
            candidates.append((dest, weight(dest)))
        total = sum(w for _, w in candidates)
        kept = [(dest, w / total) for dest, w in candidates if w / total >= MIN_SHARE]
        norm = sum(share for _, share in kept)
        vph = weight(origin) * scale
        for dest, share in kept:
            out.append((f"{origin.getID()}__{dest.getID()}", origin.getID(), dest.getID(), vph * share / norm))
    return out


def write(path: Path, rows: list[tuple[str, str, str, float]]) -> None:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- generated by build_demand.py: synthetic, not measured counts -->",
        "<routes>",
    ]
    for flow_id, origin, dest, vph in rows:
        lines.append(
            f'    <flow id="{flow_id}" type="background" begin="0" end="{HORIZON_S}" from="{origin}" to="{dest}" '
            f'probability="{vph / 3600:.5f}" departLane="best" departSpeed="max" departPos="base"/>'
        )
    lines.append("</routes>")
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    parser = argparse.ArgumentParser(description="Synthetic demand for pittsburgh_oakland")
    parser.add_argument("--net", type=Path, default=NET)
    parser.add_argument("--scale", type=float, default=DEFAULT_SCALE)
    parser.add_argument("--out", type=Path, default=HERE / "demand.rou.xml")
    args = parser.parse_args()

    net = sumolib.net.readNet(str(args.net))
    rows = flows(net, args.scale)
    write(args.out, rows)
    entries, exits = boundary_edges(net)
    by_class = collections.Counter(road_class(e) for e in entries)
    print(
        f"wrote {args.out.name}: {len(rows)} flows from {len(entries)} entries {dict(by_class)} to {len(exits)} exits, "
        f"{sum(r[3] for r in rows):.0f} veh/h (scale {args.scale})"
    )


if __name__ == "__main__":
    main()
