"""Generate continuous background demand for the downtown_grid scenario.

Every boundary road is an entry and an exit. Each entry has an hourly volume;
most vehicles continue straight through, the rest spread across the other
exits. Flows use per-second insertion probabilities (Poisson-like arrivals) so
traffic looks natural; runs stay reproducible because SUMO's RNG is seeded and
included in saved simulation state.

Usage:
    python simulation/scenarios/downtown_grid/build_demand.py
"""

from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent

# boundary node -> (entry edge, exit edge, veh/h entering, straight-through exit node)
BOUNDARY = {
    "W1": ("W1_A1", "A1_W1", 150, "E1"),
    "W2": ("W2_A2", "A2_W2", 750, "E2"),  # Main St eastbound is the peak commute direction
    "W3": ("W3_A3", "A3_W3", 150, "E3"),
    "E1": ("E1_C1", "C1_E1", 150, "W1"),
    "E2": ("E2_C2", "C2_E2", 450, "W2"),
    "E3": ("E3_C3", "C3_E3", 150, "W3"),
    "SA": ("SA_A1", "A1_SA", 120, "NA"),
    "SB": ("SB_B1", "B1_SB", 400, "NB"),
    "SC": ("SC_C1", "C1_SC", 120, "NC"),
    "NA": ("NA_A3", "A3_NA", 120, "SA"),
    "NB": ("NB_B3", "B3_NB", 400, "SB"),
    "NC": ("NC_C3", "C3_NC", 120, "SC"),
}
STRAIGHT_SHARE = 0.7
HORIZON_S = 24 * 3600


def flows() -> list[tuple[str, str, str, float]]:
    out = []
    for origin, (entry, _exit, volume, straight) in BOUNDARY.items():
        others = [d for d in BOUNDARY if d not in (origin, straight)]
        for dest in [straight, *others]:
            share = STRAIGHT_SHARE if dest == straight else (1 - STRAIGHT_SHARE) / len(others)
            vph = volume * share
            out.append((f"{origin}_to_{dest}", entry, BOUNDARY[dest][1], vph))
    return out


def build() -> Path:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- generated by build_demand.py -->",
        "<routes>",
    ]
    for fid, entry, exit_, vph in flows():
        lines.append(
            f'    <flow id="{fid}" type="background" begin="0" end="{HORIZON_S}" '
            f'from="{entry}" to="{exit_}" probability="{vph / 3600:.5f}" '
            f'departLane="best" departSpeed="max" departPos="base"/>'
        )
    lines.append("</routes>")
    out = HERE / "demand.rou.xml"
    out.write_text("\n".join(lines) + "\n")
    total = sum(v for *_, v in flows())
    print(f"wrote {out.name}: {len(flows())} flows, {total:.0f} veh/h total")
    return out


if __name__ == "__main__":
    build()
