"""Generate the synthetic 3x3 downtown grid used by the MVP.

Layout (north is up, 250 m blocks, 200 m approach roads):

            NA        NB        NC
            |         |         |
    W3 --- A3 ------ B3 ------ C3 --- E3      Park St
            |         |         |
    W2 === A2 ====== B2 ====== C2 === E2      Main St   (2 lanes / direction)
            |         ‖         |
    W1 --- A1 ------ B1 ------ C1 --- E1      Harbor St
            |         ‖         |
            SA        SB        SC
          Oak Ave  Central Ave  Pine Ave
                   (2 lanes / direction)

All nine interior junctions are signalized. Edge ids are "<from>_<to>"
(e.g. "B2_C2" is Main St eastbound between Central Ave and Pine Ave).

Usage:
    python simulation/networks/grid3x3/build_network.py
Requires SUMO's `netconvert` (bundled with `pip install eclipse-sumo`).
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import quoteattr

HERE = Path(__file__).resolve().parent
NAME = "grid3x3"

BLOCK = 250.0  # distance between signalized intersections (m)
APPROACH = 200.0  # length of the roads feeding the grid from outside (m)

COLUMNS = ["A", "B", "C"]  # west -> east
ROWS = [1, 2, 3]  # south -> north

AVENUES = {"A": "Oak Ave", "B": "Central Ave", "C": "Pine Ave"}  # north-south
STREETS = {1: "Harbor St", 2: "Main St", 3: "Park St"}  # east-west

MAJOR_AVENUES = {"B"}
MAJOR_STREETS = {2}

# Eastbound green wave: each column's signals start their cycle one block's
# travel time (250 m at 50 km/h ~= 18 s) after the column to its west.
GREEN_WAVE_OFFSET_S = 18

MAJOR = {"lanes": 2, "speed": 13.89, "priority": 3}  # 50 km/h
MINOR = {"lanes": 1, "speed": 11.11, "priority": 2}  # 40 km/h


def _nodes() -> list[tuple[str, float, float, str]]:
    nodes: list[tuple[str, float, float, str]] = []
    for ci, col in enumerate(COLUMNS):
        for row in ROWS:
            nodes.append((f"{col}{row}", ci * BLOCK, (row - 1) * BLOCK, "traffic_light"))
    max_x = (len(COLUMNS) - 1) * BLOCK
    max_y = (len(ROWS) - 1) * BLOCK
    for row in ROWS:
        y = (row - 1) * BLOCK
        nodes.append((f"W{row}", -APPROACH, y, "priority"))
        nodes.append((f"E{row}", max_x + APPROACH, y, "priority"))
    for ci, col in enumerate(COLUMNS):
        x = ci * BLOCK
        nodes.append((f"S{col}", x, -APPROACH, "priority"))
        nodes.append((f"N{col}", x, max_y + APPROACH, "priority"))
    return nodes


def _edges() -> list[dict]:
    """Return directed edges; every road is two-way."""
    roads: list[tuple[str, str, str, dict]] = []  # (a, b, name, class) a->b is west->east or south->north

    for row in ROWS:
        cls = MAJOR if row in MAJOR_STREETS else MINOR
        chain = [f"W{row}"] + [f"{c}{row}" for c in COLUMNS] + [f"E{row}"]
        for a, b in zip(chain, chain[1:]):
            roads.append((a, b, STREETS[row], cls))

    for col in COLUMNS:
        cls = MAJOR if col in MAJOR_AVENUES else MINOR
        chain = [f"S{col}"] + [f"{col}{r}" for r in ROWS] + [f"N{col}"]
        for a, b in zip(chain, chain[1:]):
            roads.append((a, b, AVENUES[col], cls))

    edges = []
    for a, b, name, cls in roads:
        for src, dst in ((a, b), (b, a)):
            edges.append(
                {
                    "id": f"{src}_{dst}",
                    "from": src,
                    "to": dst,
                    "name": name,
                    "numLanes": cls["lanes"],
                    "speed": cls["speed"],
                    "priority": cls["priority"],
                }
            )
    return edges


def write_plain_xml() -> tuple[Path, Path]:
    nod = HERE / f"{NAME}.nod.xml"
    edg = HERE / f"{NAME}.edg.xml"
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<!-- generated by build_network.py -->", "<nodes>"]
    for nid, x, y, ntype in _nodes():
        lines.append(f'    <node id="{nid}" x="{x:.2f}" y="{y:.2f}" type="{ntype}"/>')
    lines.append("</nodes>")
    nod.write_text("\n".join(lines) + "\n")

    lines = ['<?xml version="1.0" encoding="UTF-8"?>', "<!-- generated by build_network.py -->", "<edges>"]
    for e in _edges():
        lines.append(
            f'    <edge id="{e["id"]}" from="{e["from"]}" to="{e["to"]}" name={quoteattr(e["name"])} '
            f'numLanes="{e["numLanes"]}" speed="{e["speed"]:.2f}" priority="{e["priority"]}"/>'
        )
    lines.append("</edges>")
    edg.write_text("\n".join(lines) + "\n")
    return nod, edg


def find_netconvert() -> str:
    exe = shutil.which("netconvert")
    if exe:
        return exe
    try:
        import sumo  # type: ignore  # provided by `pip install eclipse-sumo`

        candidate = Path(sumo.SUMO_HOME) / "bin" / "netconvert"
        if candidate.exists():
            return str(candidate)
    except ImportError:
        pass
    sys.exit("netconvert not found: `pip install eclipse-sumo` or install SUMO and add it to PATH")


def build() -> Path:
    nod, edg = write_plain_xml()
    out = HERE / f"{NAME}.net.xml"
    cmd = [
        find_netconvert(),
        "--node-files", str(nod),
        "--edge-files", str(edg),
        "--output-file", str(out),
        "--offset.disable-normalization", "true",
        "--no-turnarounds", "true",
        "--junctions.corner-detail", "5",
        "--tls.default-type", "static",
        "--tls.cycle.time", "90",
        "--tls.yellow.time", "3",
        "--tls.allred.time", "2",
        "--no-warnings", "true",
    ]
    subprocess.run(cmd, check=True)
    apply_green_wave_offsets(out)
    print(f"wrote {out.relative_to(HERE.parents[2])}")
    return out


def apply_green_wave_offsets(net_file: Path) -> None:
    """Offset each signal so its eastbound green starts one block-travel-time after its western neighbour.

    netconvert writes offset=0 everywhere, and which phase index serves east-west
    traffic differs per junction (link order follows approach geometry), so the
    offset is derived from the program itself. SUMO delays a program by +offset.
    """
    import sumolib  # bundled with eclipse-sumo

    net = sumolib.net.readNet(str(net_file), withPrograms=True)
    offsets: dict[str, int] = {}
    for tls in net.getTrafficLights():
        program = next(iter(tls.getPrograms().values()))
        phases = program.getPhases()
        node_x, node_y = net.getNode(tls.getID()).getCoord()

        def from_west(lane) -> bool:
            from_x, from_y = lane.getEdge().getFromNode().getCoord()
            return abs(from_y - node_y) < 1.0 and from_x < node_x

        eastbound = [idx for in_lane, _out, idx in tls.getConnections() if from_west(in_lane)]
        cycle = sum(ph.duration for ph in phases)
        start = 0.0
        for ph in phases:
            if any(ph.state[i] in "Gg" for i in eastbound):
                break
            start += ph.duration
        column = COLUMNS.index(tls.getID()[0])
        offsets[tls.getID()] = int(round(column * GREEN_WAVE_OFFSET_S - start)) % int(cycle)

    text = net_file.read_text()
    for tls_id, offset in offsets.items():
        text = re.sub(rf'(<tlLogic id="{tls_id}" type="static" programID="0" offset=")[-0-9.]+"', rf'\g<1>{offset}"', text)
    net_file.write_text(text)


if __name__ == "__main__":
    build()
